added mysqldump with two users to start the application. excluded cglib cglib-full jar file from the distribution it causes nested exception is java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(I)V: java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(I)V